### ISSUE TITLE
Error: Could not find Xcode version that satisfied version spec: '14'

### ISSUE THREAD

**Issue by lukepighetti** [cirruslabs/macos-image-templates#76]
Currently getting this error on latest (`14.3-beta`) when trying to use `maxim-lobanov/setup-xcode@v1`

```
Prepare all required actions
[2](https://github.com/tonalfitness/mobile/actions/runs/4226284165/jobs/7339663969#step:4:2)
Getting action download info
[3](https://github.com/tonalfitness/mobile/actions/runs/4226284165/jobs/7339663969#step:4:3)
Download action repository 'actions/cache@v3' (SHA:6998d139ddd3e68c71e9e398d8e40b71a2f39812)
[4](https://github.com/tonalfitness/mobile/actions/runs/4226284165/jobs/7339663969#step:4:4)
Download action repository 'maxim-lobanov/setup-cocoapods@v1' (SHA:31e82105189a8cffe06c0d8da5cd9bd79d49d258)
[5](https://github.com/tonalfitness/mobile/actions/runs/4226284165/jobs/7339663969#step:4:5)
Run ./.github/actions/setup-cocoapods
[8](https://github.com/tonalfitness/mobile/actions/runs/4226284165/jobs/7339663969#step:4:9)
Prepare all required actions
[9](https://github.com/tonalfitness/mobile/actions/runs/4226284165/jobs/7339663969#step:4:10)
Getting action download info
[10](https://github.com/tonalfitness/mobile/actions/runs/4226284165/jobs/7339663969#step:4:11)
Download action repository 'maxim-lobanov/setup-xcode@v1' (SHA:9a697e2b393340c3cacd97468baa318e4c883d98)
[11](https://github.com/tonalfitness/mobile/actions/runs/4226284165/jobs/7339663969#step:4:12)
Run ./.github/actions/setup-xcode
[12](https://github.com/tonalfitness/mobile/actions/runs/4226284165/jobs/7339663969#step:4:14)
Run maxim-lobanov/setup-xcode@v1
[15](https://github.com/tonalfitness/mobile/actions/runs/4226284165/jobs/7339663969#step:4:18)
Switching Xcode to version '14'...
[16](https://github.com/tonalfitness/mobile/actions/runs/4226284165/jobs/7339663969#step:4:19)
Available versions:
[17](https://github.com/tonalfitness/mobile/actions/runs/4226284165/jobs/7339663969#step:4:20)
┌─────────┬──────────┬─────────────┬─────────────┬────────┬──────────────────────────────────┐
[18](https://github.com/tonalfitness/mobile/actions/runs/4226284165/jobs/7339663969#step:4:21)
│ (index) │ version  │ buildNumber │ releaseType │ stable │               path               │
[19](https://github.com/tonalfitness/mobile/actions/runs/4226284165/jobs/7339663969#step:4:22)
├─────────┼──────────┼─────────────┼─────────────┼────────┼──────────────────────────────────┤
[20](https://github.com/tonalfitness/mobile/actions/runs/4226284165/jobs/7339663969#step:4:23)
│    0    │ '14.3.0' │ '14E5197f'  │   'Beta'    │ false  │ '/Applications/Xcode-14.3.0.app' │
[21](https://github.com/tonalfitness/mobile/actions/runs/4226284165/jobs/7339663969#step:4:24)
└─────────┴──────────┴─────────────┴─────────────┴────────┴──────────────────────────────────┘
[22](https://github.com/tonalfitness/mobile/actions/runs/4226284165/jobs/7339663969#step:4:25)
Error: Could not find Xcode version that satisfied version spec: '14'
```

```yaml
name: Setup Xcode
description: Switch to correct version of Xcode

runs:
  using: composite
  steps:
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 14
```

```yaml
  swiftlint:
    timeout-minutes: 10
    runs-on: ghcr.io/cirruslabs/macos-ventura-xcode:14
    steps:
      # ...
      - name: Setup Xcode
        uses: ./.github/actions/setup-xcode
      # ...
```
